specfile_path: anaconda.spec
upstream_package_name: anaconda
upstream_tag_template: anaconda-{version}-1
actions:
  create-archive:
    - ./autogen.sh
    - ./configure
    - "make release"
    - 'bash -c "ls -1 anaconda-*.tar.bz2"'
jobs:
  - job: tests
    trigger: pull_request
    metadata:
      targets:
        - fedora-rawhide

  - job: copr_build
    trigger: pull_request
    metadata:
      targets:
        - fedora-rawhide
#        - fedora-eln

  - job: copr_build
    trigger: commit
    metadata:
      targets:
        - fedora-rawhide
        - fedora-eln
      branch: master
      owner: "@rhinstaller"
      project: Anaconda
      preserve_project: True
      additional_repos:
        - "copr://@storage/blivet-daily"

  - job: copr_build
    trigger: commit
    metadata:
      targets:
        - fedora-latest
      branch: f34-devel
      owner: "@rhinstaller"
      project: Anaconda-devel
      preserve_project: True
      additional_repos:
        - "copr://@storage/blivet-daily"
